### ISSUE TITLE
docs website is broken

### ISSUE THREAD

**Issue by minimapletinytools** [jbh-cloud/spotify_sync#35]
The links in the doc website are broken 

https://docs.spotify-sync.jbh.cloud/spotify-sync/

**Comment by minimapletinytools** [comment]
Could the docs be added to github repo so program instructions are self-contained and can be self-hosted if needed?

**Comment by jbh-cloud** [comment]
Unsure where you got that url but the docs site is up, just without that path:

https://docs.spotify-sync.jbh.cloud/

Makes sense to have the docs embedded in the repo

**Comment by minimapletinytools** [comment]
Oh, apparently you get to that link if you click on that "spotify_sync" logo at the top of the docs page.
The docs appear to be working with either link now, which resolves my issues.
Thanks!

**Comment by chkharti** [comment]
Hi, neither of the links seem to work for me. this is the message that pops up once i open either of the links: 

Ran into an issue, Error: Unable update CSP, expected value to split by in -> default-src 'self' https://static.gitbook.com; script-src 'self' 'nonce-OTEwYWZiOTItNGE2Ni00OTY0LTkzZjktZTlhNWZiMThjZjgx' 'strict-dynamic' 'unsafe-inline' 'unsafe-eval' https://static.gitbook.com https://integrations.gitbook.com https://cdn.iframe.ly; style-src 'self' https://static.gitbook.com fonts.googleapis.com 'unsafe-inline'; img-src * 'self' blob: data: files.gitbook.com https://static.gitbook.com; connect-src * 'self' integrations.gitbook.com app.gitbook.com api.gitbook.com https://static.gitbook.com; font-src 'self' fonts.gstatic.com https://static.gitbook.com; frame-src *; object-src 'none'; base-uri 'self' https://static.gitbook.com; form-action 'self' https://static.gitbook.com; frame-ancestors https:;

**Comment by ludvig-sandh** [comment]
I have the same problem as @chkharti . Seems like the website is down at the moment... I was just about to read how to create a profile to download songs because I forgot so now I cannot use the program.

**Comment by jbh-cloud** [comment]
Site should now be working (for good) via:

https://docs.spotify-sync.jbh.cloud/

**Comment by LoganWalters** [comment]
I can access the main page, but I'm getting a not found for any sub pages (ex. Profiles Configuration page)

<img width="485" alt="image" src="https://github.com/jbh-cloud/spotify_sync/assets/11477619/4edabf8f-4f08-42a2-a792-e053758d98ae">

**Comment by jbh-cloud** [comment]
Now fixed
