### ISSUE TITLE
Failure in "_exclude_playlists"

### ISSUE THREAD

**Issue by flash447** [jbh-cloud/spotify_sync#40]
Hello

Lately spotify_sync doesn't work for me anymore. It fails with:
```python
Traceback (most recent call last):
  File "/home/pi/.local/bin/spotify_sync", line 8, in <module>
    sys.exit(cli())
  File "/home/pi/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/pi/.local/lib/python3.8/site-packages/spotify_sync/__main__.py", line 48, in auto
    app.auto()
  File "/home/pi/.local/lib/python3.8/site-packages/spotify_sync/cli.py", line 57, in auto
    spotify_svc.sync()
  File "/home/pi/.local/lib/python3.8/site-packages/spotify_sync/spotify_.py", line 37, in sync
    liked, playlists = self._merge_playlist_songs(liked)
  File "/home/pi/.local/lib/python3.8/site-packages/spotify_sync/spotify_.py", line 95, in _merge_playlist_songs
    playlists = self.get_all_playlists(
  File "/home/pi/.local/lib/python3.8/site-packages/spotify_sync/spotify_.py", line 69, in get_all_playlists
    return self.paginator.user_playlists(playlists_to_exclude)
  File "/home/pi/.local/lib/python3.8/site-packages/spotify_sync/spotify_.py", line 172, in user_playlists
    return self._get_all(
  File "/home/pi/.local/lib/python3.8/site-packages/spotify_sync/spotify_.py", line 211, in _get_all
    playlists = self._exclude_playlists(
  File "/home/pi/.local/lib/python3.8/site-packages/spotify_sync/spotify_.py", line 189, in _exclude_playlists
    if playlist["name"] not in playlists_to_exclude:
TypeError: 'NoneType' object is not subscriptable
```

Any idea what is wrong?

**Comment by b4ird** [comment]
@flash447 This appears to be a playlist that you've created or followed doesn't get a name back from the API. Do you have many playlists? Is the process of elimination feasible?

**Comment by flash447** [comment]
No new playlists was created or changed (other then having songs added) around the time the problem started, so something "externally" must have happen. I will add some debug code and see what playlist is not iterated at the "traceback" and get back to you. I have around 10 playlists and all have names.

**Comment by flash447** [comment]
I have looked into this now. The particular code loops 12 times. I have created 7 playlists, which are all accounted for in the loop. There are one external playlist which have a the correct name in the loop. That leaves 4 playlists without names. Those correlate to playlists created by Spotify, such as "Discover Weekly" and "Release Radar". I haven't tested, but I assume it will work if I remove these. I updated the source code to not process playlists without names and then it seem to work.

**Comment by b4ird** [comment]
Thank you for troubleshooting this! That's weird, I've tested on my side and don't have the issue so would assume if it was the 'system' playlists it'd have the issue too. Are you able to provide some additional data from the items without a name? The schema of the response should be the same as the items array [here](https://developer.spotify.com/documentation/web-api/reference/get-a-list-of-current-users-playlists). It would probably be useful to get:

- `collaborative`
- `href`
- `id`
- `public`

Obviously if there's PII feel free to omit

**Comment by flash447** [comment]
They are all "null" from what I gathered.
I also tried to remove one of of the Spotify playlists, "Spotify TOP50-Global". Ran it again. Then there were only 3 "no name" playlists. Re-added it, then it was back to 4 again. So removing and re-adding doesn't solve anything. Very weird.

**Comment by b4ird** [comment]
I've just added your example playlist and get an id back so struggling to reproduce it. I'm hesitant to just skip playlists that don't have a name unless I can.

Can you install and run this version? It will print out all the details I care about

```
pip3 install https://github.com/b4ird/spotify_sync.git@fix-playlist-no-name
```

**Comment by b4ird** [comment]
I've just added your example playlist and get an id back so struggling to reproduce it. I'm hesitant to just skip playlists that don't have a name unless I can.

Can you install and run this version? It will print out all the details I care about

```
pip3 uninstall spot-sync && pip3 install git+https://github.com/b4ird/spotify_sync.git@fix-playlist-no-name
```

**Comment by flash447** [comment]
That fails with:
```
    f'Found playlist - name: {playlist.get("name")}, id: {playlist.get("id")}, '
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by b4ird** [comment]
My bad, try again

**Comment by flash447** [comment]
It appears that the problem is gone now. Running with your debug code, it listed only the playlists created by me. Going back to the previous version with my local work-around I noticed that it have stopped warning about no-name playlists now. So whatever was wrong, it must have been on the Spotify server-side?

**Comment by b4ird** [comment]
Hmm yeah weird one., glad it's sorted regardless
